name: widget_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/syntexalightlogo.png"

flutter_native_splash:
  color: "#FFFFFF" # Set background color
  image: assets/syntexalightlogo.png # Path to your app logo
  android: true
  ios: false


flutter:
  uses-material-design: true

  assets:
    - assets/syntexalightlogo.png
    - assets/syntexalogo.png
